theme: jekyll-theme-cayman
title: RobotChatBot
description: An AI-powered desktop assistant featuring Claude with an interactive robot interface
show_downloads: true
github:
  zip_url: https://github.com/Prithy12/RobotChatBot/releases/latest/download/Claude-Desktop-Setup-1.0.0.exe
  tar_url: https://github.com/Prithy12/RobotChatBot/releases/latest
  is_project_page: true
  repository_url: https://github.com/Prithy12/RobotChatBot