theme: jekyll-theme-cayman
title: Claude Desktop
description: A cross-platform desktop chatbot application powered by Anthropic's Claude API
show_downloads: true
github:
  zip_url: https://github.com/yourusername/claude-desktop/releases/latest
  tar_url: https://github.com/yourusername/claude-desktop/releases/latest