theme: jekyll-theme-primer
title: RobotChatBot
description: Desktop robot chatbot application powered by Claude AI
baseurl: "/RobotChatBot"
url: "https://Prithy12.github.io"
github:
  is_project_page: true
  repository_url: https://github.com/Prithy12/RobotChatBot